### ISSUE TITLE
Wrong data after import

### ISSUE THREAD

**Issue by falbarelli** [tomer-ha/LoopToIosConverter#4]
I have used your script, but unfortunately the data for one of my habits was messed up after import :( In particular the habit was marked as done on many more days that it was on the Loop Habit Tracker app on Android.

**Comment by tomer-ha** [comment]
Thanks for reporting the issue. Would you mind sharing more details, like the db file from Loop and which habit was transferred with more done days?

**Comment by falbarelli** [comment]
> Thanks for reporting the issue. Would you mind sharing more details, like the db file from Loop and which habit was transferred with more done days?

Sure, can I send the files to an email maybe instead of uploading it somewhere? Thanks you for being willing to help!

**Comment by tomer-ha** [comment]
Sure. Please send to tomer.ha@live.com

**Comment by tomer-ha** [comment]
Thanks @falbarelli. Long story short, I assumed that Loop repetitions are written to the DB only if they're "checked". It turns out that also unchecked values might be written, and they need to be filtered out.
I am not sure how does it happen, because it didn't happen in my test cases. Perhaps it happens if you check a date and then uncheck it manually.
I will create a new release soon, meanwhile I sent you by email a correct csv file.

Also - could you please edit out my email address from your comment here? :)

**Comment by falbarelli** [comment]
> Thanks @falbarelli. Long story short, I assumed that Loop repetitions are written to the DB only if they're "checked". It turns out that also unchecked values might be written, and they need to be filtered out. I am not sure how does it happen, because it didn't happen in my test cases. Perhaps it happens if you check a date and then uncheck it manually. I will create a new release soon, meanwhile I sent you by email a correct csv file.
> 
> Also - could you please edit out my email address from your comment here? :)

Thanks a lot again!
